### ISSUE TITLE
Share-button, comment-box Doesn't show when inside of ng-view

### ISSUE THREAD

**Issue by renanfranca** [wlepinski/angularjs-facebook-sdk#4]
I found the same problem here on stackoverflow (wasn't with your framework): http://stackoverflow.com/questions/18392946/facebook-comments-box-twitter-feed-broken-in-angular-symfony-web-app

Is there any workaround? I notice that profile picture works because you make an api call inside the directive.. and every time i change route it's bring the picture as expected..

**Comment by JonasPriest** [comment]
Is this problem already fixed? I included this very nice angular plugin into a project today. I tried if everything works with inserting the FacebookNameDirective. Quickly I had to notice that it only works when it was placed outside of ng-view, just like this issue states...
Was it already fixed in the latest version?
I tried to understand your workaround, renanfranca, but I'm not getting smart of the code inserted above. Could you gist it, please? That would be very kind

**Comment by cpeker** [comment]
+1

**Comment by pajingko** [comment]
I have the same problem.

**Comment by wlepinski** [comment]
I'll take a look.

**Comment by wlepinski** [comment]
@pajingko @cpeker @jverhoelen @renanfranca I just updated the plugin to version 1.1.0 (https://github.com/wlepinski/angularjs-facebook-sdk/releases/tag/v1.1.0). Please take a look at the example folder because it's working for me now. I think that the upgrade of both Angular and Facebook SDK did the trick. If this version doesn't work for you, I'll need a JSBin or something similar with a code sample of the problem.
